version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      golang: 1.13
    commands:
      - pip install --upgrade pip
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
  pre_build:
    commands:
      - go get -u github.com/aws/aws-lambda-go/...
  build:
    commands:
      - make build
  post_build:
    commands:
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-prefix countries-api/lambdas --s3-bucket test-cicd-thenesor-bucket
artifacts:
  files:
    - packaged.yaml